const landingPage = {
  hero: {
    icTravelers: "/images/ic_traveler.svg",
    icTreasures: "/images/ic_treasure.svg",
    icCities: "/images/ic_cities.svg",
    travelers: 80409,
    treasures: 882,
    cities: 1492,
  },
  mostPicked: [
    {
      _id: "asd1293uasdads1",
      name: "Jung Hook Sie",
      type: "Apartment",
      imageUrl: "/images/img-mostpicked-1.png",
      country: "South Korea",
      city: "Seoul Flore",
      price: "80",
      unit: "night",
    },
    {
      _id: "asd1293uasdads1",
      name: "The People House",
      type: "Hotel",
      imageUrl: "/images/img-mostpicked-2.png",
      country: "Indonesia",
      city: "Bogor",
      price: "52",
      unit: "night",
    },
    {
      _id: "asd1293uasdads1",
      name: "House Tour",
      type: "Rumah",
      imageUrl: "/images/img-mostpicked-3.png",
      country: "South Korea",
      city: "Seoul Flore",
      price: "80",
      unit: "night",
    },
    {
      _id: "asd1293uasdads1",
      name: "Jung Hook Sie",
      type: "Apartment",
      imageUrl: "/images/img-mostpicked-4.png",
      country: "South Korea",
      city: "Seoul Flore",
      price: "80",
      unit: "night",
    },
    {
      _id: "asd1293uasdads1",
      name: "Jung Hook Sie",
      type: "Apartment",
      imageUrl: "/images/img-mostpicked-5.png",
      country: "South Korea",
      city: "Seoul Flore",
      price: "80",
      unit: "night",
    },
  ],
  categories: [
    {
      _id: "asd1293uasdads1",
      name: "House with beauty backyard",
      items: [
        {
          _id: "asd1293uasdads1",
          name: "PSW Antasari",
          imageUrl: "/images/img-categories-1.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: true,
        },
        {
          _id: "asd1293uasdads1",
          name: "Kuretakeso",
          imageUrl: "/images/img-categories-2.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Arya Duta",
          imageUrl: "/images/img-categories-3.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Grand Dhika",
          imageUrl: "/images/img-categories-4.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
      ],
    },
    {
      _id: "asd1293uasdads1",
      name: "Hotels with large living room",
      items: [
        {
          _id: "asd1293uasdads1",
          name: "PSW Antasari",
          imageUrl: "/images/img-categories-5.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Kuretakeso",
          imageUrl: "/images/img-categories-6.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Arya Duta",
          imageUrl: "/images/img-categories-7.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Grand Dhika",
          imageUrl: "/images/img-categories-8.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: true,
        },
      ],
    },
    {
      _id: "asd1293uasdads1",
      name: "Apartments with kitchen set",
      items: [
        {
          _id: "asd1293uasdads1",
          name: "PSW Antasari",
          imageUrl: "/images/img-categories-9.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Kuretakeso",
          imageUrl: "/images/img-categories-10.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
        {
          _id: "asd1293uasdads1",
          name: "Arya Duta",
          imageUrl: "/images/img-categories-11.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: true,
        },
        {
          _id: "asd1293uasdads1",
          name: "Grand Dhika",
          imageUrl: "/images/img-categories-12.png",
          country: "South Korea",
          city: "Seoul Flore",
          isPopular: false,
        },
      ],
    },
  ],
  testimonial: {
    _id: "asd1293uasdads1",
    imageUrl: "/images/img-testimonial-1.png",
    name: "Happy Family",
    rate: 4.55,
    content:
      "What a great trip with my family and I should try again next time soon ...",
    familyName: "Angga",
    familyOccupation: "Product Designer",
  },
};

export default landingPage;
